// routes/inventory/add_new_item.js
const express = require("express");
const router = express.Router();
const prisma = require("../../config/db");
const { requireAuth, requireRole } = require("../middlewares/auth");

// POST /api/inventory/add_new_item
// Body:
// {
//   "item_name": "wire",
//   "count": 50
// }
//
// What it does:
// - Validates item_name + count
// - Normalizes item_name (trim + lowercase)
// - If item_name already exists => 409
// - Else creates new row in items with auto item_id + count
// - Returns created item (item_id, item_name, count)

router.post("/", requireAuth, requireRole("admin"), async (req, res) => {
  try {
    const rawName = req.body?.item_name;
    const rawCount = req.body?.count;

    const item_name = String(rawName || "").trim().toLowerCase();
    const countNum = Number(rawCount);

    // 1) item_name validation
    if (!item_name) {
      return res.status(400).json({
        success: false,
        message: "item_name is required",
      });
    }

    // (optional) stop crazy long names
    if (item_name.length > 50) {
      return res.status(400).json({
        success: false,
        message: "item_name is too long (max 50 chars)",
      });
    }

    // 2) count validation
    // allow 0 (new item can start with 0 stock)
    if (!Number.isFinite(countNum) || !Number.isInteger(countNum) || countNum < 0) {
      return res.status(400).json({
        success: false,
        message: "count must be an integer >= 0",
      });
    }

    // 3) Check duplicate item_name
    const existing = await prisma.items.findUnique({
      where: { item_name },
      select: { item_id: true, item_name: true },
    });

    if (existing) {
      return res.status(409).json({
        success: false,
        message: `Item '${item_name}' already exists`,
      });
    }

    // 4) Create item (item_id auto-generated by DB)
    const created = await prisma.items.create({
      data: {
        item_name,
        count: countNum,
      },
      select: {
        item_id: true,
        item_name: true,
        count: true,
      },
    });

    return res.status(201).json({
      success: true,
      message: "Item created successfully",
      item: created,
    });
  } catch (error) {
    console.error("Error creating new inventory item:", error);

    // Handle race condition: two admins try same item_name simultaneously
    const msg = String(error?.message || "");
    if (msg.includes("Unique constraint failed") || msg.includes("Duplicate") || msg.includes("unique")) {
      return res.status(409).json({
        success: false,
        message: "Item name already exists",
      });
    }

    return res.status(500).json({
      success: false,
      message: "Internal server error.",
    });
  }
});

module.exports = router;